# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 921c95e9ef023ee38714ff0a3220867b140096cc29bcf1833b1f2eadd6d391c02577557d5779f1e6dd7bc2d6b5e11b68d0181898183bf672b95c703db7001a89

test:
  secret_key_base: f5b97003ca67c3ca9091515d07eaabad95cc5779cbd257fa36eaba981f2846c36cac6d8d9404ddfc2d650c1fadb403b76e9fa0c58cb4f908556ff64c0b986ef4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
